### ISSUE TITLE
Removing Package -> Augeas ordering

### ISSUE THREAD

**Issue by treydock** [camptocamp/puppet-augeas#56]
Would a pull request to optionally disable `Package['ruby-augeas', $augeas::params::augeas_pkgs] -> Augeas <| |>` be considered?  I maintain a module that manages CentOS yum repos, https://github.com/treydock/repo_centos/tree/4.x, and recently moved all the resources from Yumrepo to Augeas to avoid annoying Puppet bugs not fixed till 4.x with regard to Yumrepo.  My puppet masters use camptocamp/puppetserver which ends up requiring this module.  This is the error I'm getting:

```
Error: Could not apply complete catalog: Found 1 dependency cycle:
(Augeas[centos-base] => Class[Repo_centos::Base] => Stage[repo_centos] => Stage[main] => Class[Augeas::Packages] => Package[augeas] => Augeas[centos-base])
```

I basically put the repo_centos code in a Stage before main, to ensure packages aren't installed from the wrong repository.

If such a pull request would be considered, any preference on how to name the parameter?

**Comment by raphink** [comment]
Actually, this relationship is not even needed with Puppet AIO.
