### ISSUE TITLE
Can't run augeas() from puppet master

### ISSUE THREAD

**Issue by ColinHebert** [camptocamp/puppet-augeas#66]
It is currently impossible to run `augeas()` from puppet master as the newer versions of puppet master use JRuby which does not allow native extensions to be used.

This issue relates to hercules-team/ruby-augeas#9 and https://tickets.puppetlabs.com/browse/MODULES-5170

Attempting to load the library leads to:
```
# puppetserver ruby -e 'require "augeas"'
LoadError: no such file to load -- _augeas
  require at org/jruby/RubyKernel.java:961
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
   <main> at /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/augeas.rb:23
  require at org/jruby/RubyKernel.java:961
   (root) at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1
   <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
```

`_augeas` being the native component.

**Comment by raphink** [comment]
Ah, that's right. I'm not sure if there's a way to fix this really…

**Comment by ColinHebert** [comment]
@raphink well it'll be mainly dependent on Hercules-team providing FFI bindings (see hercules-team/ruby-augeas#9 )
