### ISSUE TITLE
Problem running augeas resources under puppet 5

### ISSUE THREAD

**Issue by walterheck** [camptocamp/puppet-augeas#68]
We faced a problem when upgrading to puppet 5. Leaving an issue here because it should probably be fixed in this module. The error message we got is:

```
Could not evaluate: unknown error - Failed to initialize Augeas
Debug: Etc_services[clusterviewd/tcp]: Resource is being skipped, unscheduling all events
```
after hunting things down a bit it turned out that the `etc_services` module was outdated. That then lead us to diff those two versions: https://github.com/ccin2p3/puppet-etc_services/blob/v1.1.1/manifests/init.pp and https://github.com/ccin2p3/puppet-etc_services/blob/v1.0.0/manifests/init.pp.

When examined carefully it turns out that an augeas resource without `incl` and `lens` attributes will cause the above error in puppet 5.

**Comment by raphink** [comment]
Thanks for the issue. The Augeas resource is a core resource in Puppet. This module only manages the Augeas package and extra lenses, so I think the bug should be open against Puppet itself.
