### ISSUE TITLE
ruby-augeas package is not present with puppet-agent

### ISSUE THREAD

**Issue by func0der** [camptocamp/puppet-augeas#79]
Installing puppet 5.5.19 on a DEbian stretch like this:

```bash
wget -O puppet5-release-stretch.deb https://apt.puppetlabs.com/puppet5-release-stretch.deb
dpkg -i puppet5-release-stretch.deb

apt update && apt install -y puppet-agent 
puppet module install camptocamp-augeas --version 1.9.0
```

`default.pp`: 

```puppet
include ::augeas
augeas { '/etc/foo':
        provider => augeas,
}
```

```bash
$ puppet apply default.pp 
Warning: /etc/puppetlabs/code/environments/production/modules/augeas/data/common.yaml: file does not contain a valid yaml hash
Notice: Compiled catalog for foo.local in environment production in 0.28 seconds
Error: /Stage[main]/Main/Augeas[/etc/foo]: Provider augeas is not functional on this host
```

This seems to be related to this ominous AIO puppet package that you included this piece of code for:

`if versioncmp($::puppetversion, '4.0.0') >= 0 {`

I can not test it with Puppet 4 anymore, but with Puppet 5 it seems broken.

The missing package in question is `ruby-augeas`. After that is installed, everything works fine.

How can we solve this?

**Comment by raphink** [comment]
I'm guessing it's the stretch packages that are broken, as I've never seen this before with AIO packages.
