### ISSUE TITLE
Avoid "file does not contain a valid yaml hash" warning for puppetserver

### ISSUE THREAD

**Issue by XMol** [camptocamp/puppet-augeas#86]
For every catalog build with this module included, the puppetserver logs a warning with...
> Puppet /etc/puppetlabs/code/environments/production/modules/augeas/data/common.yaml: file does not contain a valid yaml hash

Please change the content of `data/common.yaml` to something that evaluates into a Hash, e.g. just `{}`, which meets this requirement, as opposed to `---`.

- Puppet version: 5.5.22
- Module version: 1.9.0

This might be an inherent problem with our Hiera data_hash setting (`lookup_key`), but `data_hash` sounds like it expects a YAML mapping, too.

**Comment by simontunnat** [comment]
We have the same issues since we upgraded to the latest version (1.9.0)

**Comment by raphink** [comment]
This should be fixed in #85

**Comment by XMol** [comment]
Thank you!
